/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package newmodulll5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SENJU
 */
public class modd5 extends javax.swing.JInternalFrame {

    DefaultListModel<String> list1 = new DefaultListModel<>();
    String nama ;
    int pilihan;
    String barang;
    String kode ;
    int harga;
    int total_harga;
    int beli=0;
    int bayar=0;
    int kembali;
    
//    DefaultTableModel tabel = new DefaultTableModel();
//    DefaultTableModel tabel = new DefaultTableModel();
//    boolean ini=true;
    /**
     * Creates new form modd5
     */
    public modd5() {
        initComponents();
        
        jList1.setModel(list1);
        tJumlah.setEditable(false);
         tKembalian.setEditable(false);
         tKode.setEditable(false);
         tHarga.setEditable(false);
         bSimpan.setText("Simpan");
         
         tampil_data();

}
        public void reset(){
        tBarang.setSelectedIndex(0);
        tKode.setText(null);
        tPembeli.setText(null);
        tHarga.setText(null);
        tTotal.setText(null);
        tBayar.setText(null);
        tKembalian.setText(null);
        beli=0;
        tJumlah.setText(null);
        bSimpan.setText("Simpan");
    
    }
        public void tampil_data(){
       DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("Nama Pembeli");
    tabel.addColumn("Nama Barang");
    tabel.addColumn("Kode Barang");
    tabel.addColumn("Harga Barang");
    tabel.addColumn("Jumlah Beli");
    tabel.addColumn("Total Harga");
    tabel.addColumn("Total Bayar");
    tabel.addColumn("Kembalian");

    try {
        java.sql.Connection conn = newmodulll5.koneksi.koneksiDB();
        String query = "SELECT * FROM tbjualan";
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet rs = stm.executeQuery(query);

        while (rs.next()) {
            Object[] data = new Object[8];
            data[0] = rs.getString("nama_pembeli");
            data[1] = rs.getString("nama_barang");
            data[2] = rs.getString("kode_barang");
            data[3] = rs.getInt("harga_barang");
            data[4] = rs.getInt("jumlah_beli");
            data[5] = rs.getInt("total_harga");
            data[6] = rs.getInt("total_bayar");
            data[7] = rs.getInt("kembalian");

            tabel.addRow(data);
        }

        // Set model tabel
        data.setModel(tabel);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tPembeli = new javax.swing.JTextField();
        tBarang = new javax.swing.JComboBox<>();
        tHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        jTambah = new javax.swing.JButton();
        jKurang = new javax.swing.JButton();
        tTotal = new javax.swing.JTextField();
        tKembalian = new javax.swing.JTextField();
        tBayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        bBayar = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bHapus1 = new javax.swing.JButton();
        bBersihkan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 51));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Nama Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Kode Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 137, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Harga Barang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 190, -1, -1));

        tPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPembeliActionPerformed(evt);
            }
        });
        jPanel2.add(tPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 36, 141, -1));

        tBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Kompor", "Pisau", "Wajan", "Panci", "Talenan", "Blender", "Mixer" }));
        tBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBarangActionPerformed(evt);
            }
        });
        jPanel2.add(tBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 83, 141, -1));

        tHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaActionPerformed(evt);
            }
        });
        jPanel2.add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 188, 141, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Nama Pembeli");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 38, -1, -1));

        tKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKodeActionPerformed(evt);
            }
        });
        jPanel2.add(tKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 135, 141, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Jumlah Beli");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 38, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Total Harga");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 85, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Kembalian");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Total Bayar");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 137, -1, -1));
        jPanel2.add(tJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 36, 48, -1));

        jTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTambah.setText("+");
        jTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahActionPerformed(evt);
            }
        });
        jPanel2.add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 33, -1, -1));

        jKurang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jKurang.setText("-");
        jKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKurangActionPerformed(evt);
            }
        });
        jPanel2.add(jKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 33, -1, -1));

        tTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalActionPerformed(evt);
            }
        });
        jPanel2.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 83, 132, -1));

        tKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembalianActionPerformed(evt);
            }
        });
        jPanel2.add(tKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 188, 132, -1));

        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        jPanel2.add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 135, 132, -1));

        data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pembeli", "Nama Barang", "Kode Barang", "Harga Barang", "Jumlah Beli", "Total Harga", "Total Bayar", "Kembalian"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 262, 720, 216));

        bBayar.setText("Bayar");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });
        jPanel2.add(bBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 228, -1, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 228, -1, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel2.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 228, -1, -1));

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        jPanel2.add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 228, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("DATA PENJUALAN ALAT DAPUR");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\baims\\Downloads\\aijooo.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        jTabbedPane1.addTab("Data", jPanel2);

        jPanel3.setBackground(new java.awt.Color(139, 193, 139));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("RIWAYAT PEMBELIAN");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jScrollPane2.setViewportView(jList1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 340, 270));

        bHapus1.setBackground(new java.awt.Color(204, 255, 204));
        bHapus1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus1.setText("HAPUS");
        bHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus1ActionPerformed(evt);
            }
        });
        jPanel3.add(bHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 420, 90, 30));

        bBersihkan.setBackground(new java.awt.Color(204, 255, 204));
        bBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBersihkan.setText("BERSIHKAN");
        bBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(bBersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\baims\\Downloads\\aehh.jpg")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 370));

        jTabbedPane1.addTab("Riwayat", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPembeliActionPerformed
        // TODO add your handling code here:
        nama = tPembeli.getText();
    }//GEN-LAST:event_tPembeliActionPerformed

    private void tKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKodeActionPerformed

    private void tTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTotalActionPerformed

    private void tKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKembalianActionPerformed

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        // TODO add your handling code here:
         bayar = Integer.parseInt(tBayar.getText());
    }//GEN-LAST:event_tBayarActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        if(data==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan direset?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
        try{
            String sql="delete from tbjualan ";
            java.sql.Connection conn=(java.sql.Connection)newmodulll5.koneksi.koneksiDB();
            java.sql.PreparedStatement 
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            reset();
            tampil_data();
            list1.addElement( "Semua data Telah Di reset ulang (Kosong)");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
            }
        }
    }//GEN-LAST:event_bResetActionPerformed

    private void tBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBarangActionPerformed
        // TODO add your handling code here:
    pilihan = tBarang.getSelectedIndex();
     if(pilihan==0){
         reset();
     }

     if(pilihan==1){
         kode = "01";
         harga = 300000;
         barang = "Kompor";
     }
     if(pilihan==2){
         kode = "02";
         harga = 20000;
         barang = "Pisau";
     }
     if(pilihan==3){
         kode = "03";
         harga = 100000;
         barang = "Wajan";
     }
     if(pilihan==4){
         kode = "04";
         harga = 30000;
         barang = "Panci";
     }
     if(pilihan==5){
         kode = "05";
         harga = 20000;
         barang = "Talenan";
     }
     if(pilihan==6){
         kode = "06";
         harga = 300000;
         barang = "Blender";
     }
     if(pilihan==7){
         kode = "07";
         harga = 700000;
         barang = "Mixer";
     }
      tKode.setText(kode);
      tHarga.setText(""+harga);
      
    }//GEN-LAST:event_tBarangActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
         try {
        String namaPembeli = tPembeli.getText(); // Ganti tNamaPembeli dengan komponen yang sesuai
        String namaBarang = (String) tBarang.getSelectedItem(); // Ganti tNamaBarang dengan komponen yang sesuai
        String kodeBarang = tKode.getText(); // Ganti tKodeBarang dengan komponen yang sesuai
        int hargaBarang = Integer.parseInt(tHarga.getText()); // Ganti tHargaBarang dengan komponen yang sesuai
        int jumlahBeli = Integer.parseInt(tJumlah.getText()); // Ganti tJumlahBeli dengan komponen yang sesuai
        int totalHarga = Integer.parseInt(tTotal.getText()); // Ganti tTotalHarga dengan komponen yang sesuai
        int totalBayar = Integer.parseInt(tBayar.getText()); // Ganti tTotalBayar dengan komponen yang sesuai
        int kembalian = Integer.parseInt(tKembalian.getText()); // Ganti tKembalian dengan komponen yang sesuai

        // Pastikan input sesuai sebelum diproses
        if (namaPembeli.isEmpty() || namaBarang.equals("Pilih Barang") || kodeBarang.isEmpty() || jumlahBeli <= 0 || totalHarga <= 0 || totalBayar <= 0 || kembalian < 0) {
            JOptionPane.showMessageDialog(null, "Tolong input data dengan benar.");
        } else {
            String query;
            String query2;
            Connection conn = null;
            PreparedStatement pst = null;

            if (bSimpan.getText().equals("Simpan")) {
                query = "INSERT INTO tbjualan (nama_pembeli, nama_barang, kode_barang, harga_barang, jumlah_beli, total_harga, total_bayar, kembalian) " +
                        "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            } else if (bSimpan.getText().equals("Edit")) {
                query = "UPDATE tbjualan SET nama_pembeli=?, nama_barang=?, kode_barang=?, harga_barang=?, jumlah_beli=?, total_harga=?, total_bayar=?, kembalian=? " +
                        "WHERE nama_pembeli=?"; // Ubah sesuai dengan kriteria update yang sesuai
                query2 = "UPDATE tbjualan SET nama_pembeli=?, nama_barang=?, kode_barang=?, harga_barang=?, jumlah_beli=?, total_harga=?, total_bayar=?, kembalian=? " +
                        "WHERE nama_pembeli=?"; // Ubah sesuai dengan kriteria update yang sesuai
            } else {
                // Handle other cases if needed
                return;
            }

            try {
                conn = newmodulll5.koneksi.koneksiDB();
                pst = conn.prepareStatement(query);

                pst.setString(1, namaPembeli);
                pst.setString(2, namaBarang);
                pst.setString(3, kodeBarang);
                pst.setInt(4, hargaBarang);
                pst.setInt(5, jumlahBeli);
                pst.setInt(6, totalHarga);
                pst.setInt(7, totalBayar);
                pst.setInt(8, kembalian);

                if (bSimpan.getText().equals("Edit")) {
                    pst.setString(9, namaPembeli); // Sesuaikan dengan kriteria update
                }

                pst.executeUpdate();
                if (bSimpan.getText().equals("Simpan")) {
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
                    reset();
                    tampil_data();
                    list1.addElement(namaPembeli + " telah Membeli Barang Dengan Kode " + kodeBarang);
                } else if (bSimpan.getText().equals("Edit")) {
                    JOptionPane.showMessageDialog(null, "Edit Berhasil disimpan");
                    reset();
                    tampil_data();
                    list1.addElement("Data pembelian dengan kode " + kodeBarang + " telah DiEdit");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal disimpan: " + e.getMessage());
            } finally {
                if (pst != null) {
                    pst.close();
                }
                if (conn != null) {
                    conn.close();
                }
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Pastikan input berupa angka pada beberapa field.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal disimpan: " + e.getMessage());
    }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void jTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahActionPerformed
        // TODO add your handling code here:
        beli++;
        tJumlah.setText(Integer.toString(beli));
        total_harga = beli*harga;
        tTotal.setText(""+total_harga);
    }//GEN-LAST:event_jTambahActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
    int total_harga = Integer.parseInt(tTotal.getText());
    int bayar = Integer.parseInt(tBayar.getText());
    
    if (bayar < total_harga) {
        JOptionPane.showMessageDialog(null, "Pembayaran kurang, tolong masukkan pembayaran yang sesuai.");
    } else {
        int kembali = bayar - total_harga;
        tKembalian.setText(String.valueOf(kembali));
    }
    }//GEN-LAST:event_bBayarActionPerformed

    private void jKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKurangActionPerformed
        // TODO add your handling code here:
        beli--;
       tJumlah.setText(Integer.toString(beli));
         if (beli<0){
         tJumlah.setText("0");
         beli=0;
       }
      tJumlah.setText(Integer.toString(beli));
      total_harga = beli*harga;
      tTotal.setText(""+total_harga);
    }//GEN-LAST:event_jKurangActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        int baris = data.rowAtPoint(evt.getPoint());
       
        String a = data.getValueAt(baris, 0).toString();
        tPembeli.setText(a);
        String b = data.getValueAt(baris, 1).toString();
        tBarang.setSelectedItem(b);
        String c = data.getValueAt(baris, 2).toString();
        tKode.setText(c);
        String d = data.getValueAt(baris, 3).toString();
        tHarga.setText(d);
        String e = data.getValueAt(baris, 4).toString();
        tJumlah.setText(e);
        String f = data.getValueAt(baris, 5).toString();
        tTotal.setText(f);
        String g = data.getValueAt(baris, 6).toString();
        tBayar.setText(g);
        String h = data.getValueAt(baris, 7).toString();
        tKembalian.setText(h);
        bSimpan.setText("Edit");
    }//GEN-LAST:event_dataMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here
        if(data==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
         }else if(tKode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus!");
        } else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan dihapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
               try{
               String sql="delete from tbjualan where kode_barang ='"+kode+"'";
               java.sql.Connection conn=(java.sql.Connection)newmodulll5.koneksi.koneksiDB();
               java.sql.PreparedStatement 
               pst=conn.prepareStatement(sql);
               pst.execute();
               JOptionPane.showMessageDialog(null, "Berhasil dihapus");
               tampil_data();
               reset();
               list1.addElement( "Data pembelian dengan kode " + kode + " telah Dihapus ");
               
               }
            catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
            } 
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihkanActionPerformed
        // TODO add your handling code here:
        if (list1.isEmpty()){
        JOptionPane.showMessageDialog(this,"Data Kosong");
        }else{
        list1.clear();
        }
    }//GEN-LAST:event_bBersihkanActionPerformed

    private void tHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaActionPerformed

    private void bHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();

    // Mendapatkan indeks item yang dipilih
    int selectedIndex = jList1.getSelectedIndex();
    
    if (selectedIndex != -1) {
        // Menghapus item terpilih dari list
        model.remove(selectedIndex);
    }
    }//GEN-LAST:event_bHapus1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHapus1;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JTable data;
    private javax.swing.JButton jKurang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jTambah;
    private javax.swing.JComboBox<String> tBarang;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tKembalian;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tPembeli;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables

//    private void updatejList1() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

}
